import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import NavBar from "./myComponents/NavBar";
import SideBar from "./myComponents/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="flex min-h-screen">
            <SideBar />
            <div className="flex-1 p-4 overflow-y-auto bg-black">
              <NavBar />
              {children}
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
